URL_SERVICE: str = "https://f188e54f-ced2-496e-8ea3-8db6c66572b5.serverhub.praktikum-services.ru"

PATH_CREATE_COURIER: str = "/api/v1/courier"
PATH_LOGIN_COURIER: str = "/api/v1/courier/login"
PATH_DELETE_COURIER: str = "/api/v1/courier/{courier_id}"
PATH_CREATE_ORDER: str = "/api/v1/orders"
PATH_GET_ORDER: str = "/api/v1/orders/track"
PATH_ACCEPT_ORDER: str = "/api/v1/orders/accept/{order_id}?courierId={courier_id}"
PATH_FINISH_ORDER: str = "/api/v1/orders/finish/{order_id}"
PATH_CANCEL_ORDER: str = "/api/v1/orders/cancel?track={order_track_id}"
