URL_SERVICE: str = "https://6f88a204-7e13-4bf6-ba9f-a739f470cd5a.serverhub.praktikum-services.ru"

PATH_CREATE_COURIER: str = "/api/v1/courier"
PATH_LOGIN_COURIER: str = "/api/v1/courier/login"
PATH_DELETE_COURIER: str = "/api/v1/courier/{courier_id}"
PATH_CREATE_ORDER: str = "/api/v1/orders"
PATH_GET_ORDER: str = "/api/v1/orders/track"
PATH_ACCEPT_ORDER: str = "/api/v1/orders/accept/{order_id}?courierId={courier_id}"
PATH_FINISH_ORDER: str = "/api/v1/orders/finish/{order_id}"
PATH_CANCEL_ORDER: str = "/api/v1/orders/cancel?track={order_track_id}"
